version: '3'

services:
    bot_web:
        build: .
        ports:
            - "8000:8000"
    db:
        image: postgres:13
        expose:
            - 5433
        ports:
            - 5433:5433
        environment:
            - POSTGRES_PASSWORD=
            - POSTGRES_USER=
            - POSTGRES_DB=
        command: -p 5433