version: '3'

services:
    web:
        build: .
        ports:
            - ${WEB_PORT}:${WEB_PORT}
        depends_on:
            - db
        volumes:
            - .:/code/
        command: python manage.py runserver 0.0.0.0:${WEB_PORT}

    bot:
        build: .
        depends_on:
            - db
        volumes:
            - .:/code/
        restart: always
        command: python manage.py bot

    db:
        image: postgres:13
        expose:
            - ${DB_PORT}
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        command: -p ${DB_PORT}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
        external: true

