# Generated by Django 4.1.6 on 2023-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('type', models.CharField(choices=[('CW', 'Коворкинг'), ('F', 'Место питания')], max_length=15, verbose_name='Тип')),
                ('attributes', models.JSONField(verbose_name='Аттрибуты')),
                ('working_hours', models.JSONField(verbose_name='Часы работы')),
                ('ymap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yandex maps')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='TG ID')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='TG username')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'TG пользователь',
                'verbose_name_plural': 'TG пользователи',
                'ordering': ['created_at'],
            },
        ),
    ]
